version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'vit-pg'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=vit_db'

  java_app:
    build: ./
    container_name: 'vit-app'
    ports:
      - '8081:8080'